import { KeyLabel } from "@/app/components/keyboard"

export const shinThreeSetLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅢ', labelType: 'vowel'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㅐ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '\"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㅔ', labelType: 'vowel'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '/'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSet2003Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㅐ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '“'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '”'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: 'ㅢ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '‘'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '’'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '\"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: '※'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㅔ', labelType: 'vowel'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '/'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSet2015Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅒ', labelType: 'vowel'}], topLabels: [{label: 'ㅎ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: 'ㅁ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅇ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '《'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '》'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '…'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: 'ㅆ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: 'ㄴ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄹ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '〈'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '〉'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: 'ㅂ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: 'ㄱ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅅ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSetMLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅒ', labelType: 'vowel'}], topLabels: [{label: 'ㅅ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: 'ㄹ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅂ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '“'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '”'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '※'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: 'ㅇ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: 'ㄴ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㅆ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '《'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '》'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: 'ㅁ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: 'ㄱ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅎ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSetMJejuLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅒ', labelType: 'vowel'}], topLabels: [{label: 'ㅅ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: 'ㄹ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅂ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: 'ᆢ', labelType: 'vowel', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '※'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: 'ㅇ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: 'ㄴ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㅆ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '《'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '》'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: 'ㅁ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: 'ㄱ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅎ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSetP2Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: 'ㅐ', labelType: 'vowel'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '×'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '○'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}, {label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}, {label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}, {label: 'ㆍ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '□'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅔ', labelType: 'vowel'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '―'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '…'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSetP2OldLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: 'ㅐ', labelType: 'vowel'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: ' 〯', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: ' 〮', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}, {label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}, {label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}, {label: 'ㆍ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '□'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅔ', labelType: 'vowel'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '―'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '…'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const shinThreeSetHSLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㅐ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '×'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '○'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}, {label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '`'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}, {label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '~'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '×'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㅢ', labelType: 'vowel'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '□'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '.'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅔ', labelType: 'vowel'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '―'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '…'}]},
    {keyCode: ',', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: ','}], topLabels: [{label: '?'}]},
  ],
]
export const chamShinThreeSetLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}, {label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '「'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}, {label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: '」'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: '『'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}, {label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: '』'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: '□'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '※'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '←'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '→'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '―'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}, {label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: '‘'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}, {label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: '’'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: '“'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: '”'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}, {label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: '○'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '×'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '…'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '/'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '\"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}, {label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '〈'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅒ', labelType: 'vowel'}, {label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: '〉'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}, {label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: '《'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}, {label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: '》'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '△'}, {label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '❖'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}, {label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '?'}]},
  ],
]
export const chamShinThreeSetDLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}, {label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}, {label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}, {label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}, {label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '「'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}, {label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: '」'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: '『'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}, {label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: '』'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: '□'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '※'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '←'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '→'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}, {label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '―'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}, {label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: '‘'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}, {label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: '’'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: '“'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '”'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '○'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '×'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '…'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '/'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '\"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}, {label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '〈'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅒ', labelType: 'vowel'}, {label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: '〉'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}, {label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: '《'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: '》'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}, {label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '△'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '❖'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}, {label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '?'}]},
  ],
]
