import { KeyLabel } from "@/app/components/keyboard";

export const threeSetSemoELayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: '1', labelType: 'normal'}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: '2', labelType: 'normal'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: '3', labelType: 'normal'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: '4', labelType: 'normal'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: '5', labelType: 'normal'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: '6', labelType: 'normal'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: '7', labelType: 'normal'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: '8', labelType: 'normal'}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: '9', labelType: 'normal'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: '0', labelType: 'normal'}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}, {label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: '↔', labelType: 'normal'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}, {label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: '↑', labelType: 'normal'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}, {label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: '♡', labelType: 'normal'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}, {label: 'ㅝ', labelType: 'vowel'}], topLabels: [{label: '☆', labelType: 'normal'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅒ', labelType: 'vowel'}], topLabels: [{label: '◎', labelType: 'normal'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '×', labelType: 'normal'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '○', labelType: 'normal'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '〈', labelType: 'normal'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: '〉', labelType: 'normal'}]},
    {keyCode: 'p', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: ';', labelType: 'normal'}]},
    {keyCode: '[', bottomLabels: [{label: '[', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: ']', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}, {label: 'ㅀ', labelType: 'trailing'}], topLabels: [{label: '←', labelType: 'normal'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}, {label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: '↓', labelType: 'normal'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅚ', labelType: 'vowel'}], topLabels: [{label: '→', labelType: 'normal'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㅘ', labelType: 'vowel'}], topLabels: [{label: '△', labelType: 'normal'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}, {label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '▽', labelType: 'normal'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '□', labelType: 'normal'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '기호', labelType: 'normal'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '※', labelType: 'normal'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '·', labelType: 'normal'}]},
    {keyCode: ';', bottomLabels: [{label: '종⇧', labelType: 'trailing'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '\'', labelType: 'normal'}], topLabels: [{label: '\"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}, {label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: '『', labelType: 'normal'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}, {label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '』', labelType: 'normal'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '「', labelType: 'normal'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}, {label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '」', labelType: 'normal'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}, {label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '°', labelType: 'normal'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '―', labelType: 'normal'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '…', labelType: 'normal'}]},
    {keyCode: ',', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: '중⇧', labelType: 'vowel'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: '/', labelType: 'normal'}], topLabels: [{label: '?', labelType: 'normal'}]},
  ],
];
export const threeSetSemoEOldLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅿ', labelType: 'trailing'}, {label: 'ᅟᅠퟗ', labelType: 'trailing', requiresOldHangulFont: true}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㆁ', labelType: 'trailing'}, {label: 'ㆆ', labelType: 'trailing'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅭ', labelType: 'trailing'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㄽ', labelType: 'trailing'}, {label: 'ㅽ', labelType: 'trailing'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㆉ', labelType: 'vowel'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㆌ', labelType: 'vowel'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㆎ', labelType: 'vowel'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅿ', labelType: 'leading'}, {label: 'ꥶᅠ', labelType: 'leading', requiresOldHangulFont: true}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㆀ', labelType: 'leading'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅄ', labelType: 'leading'}, {label: 'ᅋᅠ', labelType: 'leading', requiresOldHangulFont: true}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}, {label: 'ㅊ', labelType: 'trailing'}, {label: 'ㅼ', labelType: 'trailing'}], topLabels: [{label: '↔', labelType: 'normal'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}, {label: 'ㅍ', labelType: 'trailing'}, {label: 'ㅸ', labelType: 'trailing'}], topLabels: [{label: '↑', labelType: 'normal'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}, {label: 'ㅈ', labelType: 'trailing'}, {label: 'ㅪ', labelType: 'trailing'}], topLabels: [{label: '♡', labelType: 'normal'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}, {label: 'ㅝ', labelType: 'vowel'}, {label: 'ᅟᅺ', labelType: 'vowel', requiresOldHangulFont: true}], topLabels: [{label: '☆', labelType: 'normal'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅒ', labelType: 'vowel'}, {label: 'ᅟᅽ', labelType: 'vowel', requiresOldHangulFont: true}], topLabels: [{label: '◎', labelType: 'normal'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}, {label: 'ㅱ', labelType: 'leading'}], topLabels: [{label: ' 〯', labelType: 'normal', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: ' 〮', labelType: 'normal', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}, {label: 'ㅦ', labelType: 'leading'}], topLabels: [{label: '〈', labelType: 'normal'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}, {label: 'ㅸ', labelType: 'leading'}], topLabels: [{label: '〉', labelType: 'normal'}]},
    {keyCode: 'p', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: ';', labelType: 'normal'}]},
    {keyCode: '[', bottomLabels: [{label: '[', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: ']', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}, {label: 'ㅀ', labelType: 'trailing'}, {label: 'ㆄ', labelType: 'trailing'}], topLabels: [{label: '←', labelType: 'normal'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}, {label: 'ㅎ', labelType: 'trailing'}, {label: 'ㅦ', labelType: 'trailing'}], topLabels: [{label: '↓', labelType: 'normal'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅚ', labelType: 'vowel'}, {label: 'ᅟᆜ', labelType: 'vowel', requiresOldHangulFont: true}], topLabels: [{label: '→', labelType: 'normal'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㅘ', labelType: 'vowel'}], topLabels: [{label: '△', labelType: 'normal'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}, {label: 'ㅑ', labelType: 'vowel'}, {label: 'ᅟힺ', labelType: 'vowel', requiresOldHangulFont: true}], topLabels: [{label: '▽', labelType: 'normal'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}, {label: 'ㆆ', labelType: 'leading'}], topLabels: [{label: '□', labelType: 'normal'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}, {label: 'ㆁ', labelType: 'leading'}], topLabels: [{label: '기호', labelType: 'normal'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}, {label: 'ㅷ', labelType: 'leading'}], topLabels: [{label: '※', labelType: 'normal'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}, {label: 'ㆄ', labelType: 'leading'}], topLabels: [{label: '·', labelType: 'normal'}]},
    {keyCode: ';', bottomLabels: [{label: '종⇧', labelType: 'trailing'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '\'', labelType: 'normal'}], topLabels: [{label: '\"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}, {label: 'ㄷ', labelType: 'trailing'}, {label: 'ㅱ', labelType: 'trailing'}], topLabels: [{label: '『', labelType: 'normal'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}, {label: 'ㅋ', labelType: 'trailing'}, {label: 'ㅺ', labelType: 'trailing'}], topLabels: [{label: '』', labelType: 'normal'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '「', labelType: 'normal'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}, {label: 'ㅛ', labelType: 'vowel'}, {label: 'ᅟᅸ', labelType: 'vowel', requiresOldHangulFont: true}], topLabels: [{label: '」', labelType: 'normal'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}, {label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '°', labelType: 'normal'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '―', labelType: 'normal'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}, {label: 'ᄛᅠ', labelType: 'leading', requiresOldHangulFont: true}], topLabels: [{label: '…', labelType: 'normal'}]},
    {keyCode: ',', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: '중⇧', labelType: 'vowel'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: '/', labelType: 'normal'}], topLabels: [{label: '?', labelType: 'normal'}]},
  ],
];
export const threeSetAhnmataeLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: '1', labelType: 'normal'}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: '2', labelType: 'normal'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: '3', labelType: 'normal'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: '4', labelType: 'normal'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: '5', labelType: 'normal'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: '6', labelType: 'normal'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: '7', labelType: 'normal'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: '8', labelType: 'normal'}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: '9', labelType: 'normal'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: '0', labelType: 'normal'}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: []},
    {keyCode: 'w', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: 'ㅿ', labelType: 'leading'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: []},
    {keyCode: 'r', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: []},
    {keyCode: 't', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: 'ㆆ', labelType: 'leading'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: ';', labelType: 'normal'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '\'', labelType: 'normal'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '/', labelType: 'normal'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '[', labelType: 'normal'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: ']', labelType: 'normal'}]},
    {keyCode: '[', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: '?', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: []},
    {keyCode: 's', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: []},
    {keyCode: 'd', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: []},
    {keyCode: 'f', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: []},
    {keyCode: 'g', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: 'ㆁ', labelType: 'leading'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'j', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'l', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: []},
    {keyCode: ';', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: '\"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: []},
    {keyCode: 'x', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: []},
    {keyCode: 'c', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: []},
    {keyCode: 'v', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: []},
    {keyCode: 'b', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㆁ', labelType: 'trailing'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅿ', labelType: 'trailing'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: []},
    {keyCode: ',', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㆆ', labelType: 'trailing'}]},
  ],
];
