import { KeyLabel } from "@/app/components/keyboard";

export const twoSetLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: '1', labelType: 'normal'}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: '2', labelType: 'normal'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: '3', labelType: 'normal'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: '4', labelType: 'normal'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: '5', labelType: 'normal'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: '6', labelType: 'normal'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: '7', labelType: 'normal'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: '8', labelType: 'normal'}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: '9', labelType: 'normal'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: '0', labelType: 'normal'}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'u', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'i', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '[', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: ']', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'f', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'g', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'j', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: []},
    {keyCode: ';', bottomLabels: [{label: ';', labelType: 'normal'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '\'', labelType: 'normal'}], topLabels: [{label: '"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'n', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'm', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: []},
    {keyCode: ',', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: '/', labelType: 'normal'}], topLabels: [{label: '?', labelType: 'normal'}]},
  ],
];
export const twoSetOldLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: '1', labelType: 'normal'}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: '2', labelType: 'normal'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: '3', labelType: 'normal'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: '4', labelType: 'normal'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: '5', labelType: 'normal'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: '6', labelType: 'normal'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: '7', labelType: 'normal'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: '8', labelType: 'normal'}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: '9', labelType: 'normal'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: '0', labelType: 'normal'}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: ' 〯', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: ' 〮', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '[', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: ']', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}], topLabels: [{label: 'ㅿ', labelType: 'consonant'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}], topLabels: [{label: 'ㆁ', labelType: 'consonant'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'g', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}], topLabels: [{label: 'ㆆ', labelType: 'consonant'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'j', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: []},
    {keyCode: ';', bottomLabels: [{label: ';', labelType: 'normal'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '\'', labelType: 'normal'}], topLabels: [{label: '"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}], topLabels: [{label: 'ᄼᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}], topLabels: [{label: 'ᄾᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}], topLabels: [{label: 'ᅎᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}], topLabels: [{label: 'ᅐᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: 'ᅔᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: 'ᅕᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '❖', labelType: 'normal'}]},
    {keyCode: ',', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: '/', labelType: 'normal'}], topLabels: [{label: '?', labelType: 'normal'}]},
  ],
];
export const dujulELayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: '1', labelType: 'normal'}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: '2', labelType: 'normal'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: '3', labelType: 'normal'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: '4', labelType: 'normal'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: '5', labelType: 'normal'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: '6', labelType: 'normal'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: '7', labelType: 'normal'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: '8', labelType: 'normal'}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: '9', labelType: 'normal'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: '0', labelType: 'normal'}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'u', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'i', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'o', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'p', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: ';', labelType: 'normal'}]},
    {keyCode: '[', bottomLabels: [{label: '[', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: ']', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'f', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'j', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: []},
    {keyCode: ';', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '\'', labelType: 'normal'}], topLabels: [{label: '"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'v', bottomLabels: [{label: 'ㅆ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'b', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'n', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: '/', labelType: 'normal'}], topLabels: [{label: '?', labelType: 'normal'}]},
  ],
];
export const dugyeobELayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩', labelType: 'normal'}], topLabels: [{label: '~', labelType: 'normal'}]},
    {keyCode: '1', bottomLabels: [{label: '1', labelType: 'normal'}], topLabels: [{label: '!', labelType: 'normal'}]},
    {keyCode: '2', bottomLabels: [{label: '2', labelType: 'normal'}], topLabels: [{label: '@', labelType: 'normal'}]},
    {keyCode: '3', bottomLabels: [{label: '3', labelType: 'normal'}], topLabels: [{label: '#', labelType: 'normal'}]},
    {keyCode: '4', bottomLabels: [{label: '4', labelType: 'normal'}], topLabels: [{label: '$', labelType: 'normal'}]},
    {keyCode: '5', bottomLabels: [{label: '5', labelType: 'normal'}], topLabels: [{label: '%', labelType: 'normal'}]},
    {keyCode: '6', bottomLabels: [{label: '6', labelType: 'normal'}], topLabels: [{label: '^', labelType: 'normal'}]},
    {keyCode: '7', bottomLabels: [{label: '7', labelType: 'normal'}], topLabels: [{label: '&', labelType: 'normal'}]},
    {keyCode: '8', bottomLabels: [{label: '8', labelType: 'normal'}], topLabels: [{label: '*', labelType: 'normal'}]},
    {keyCode: '9', bottomLabels: [{label: '9', labelType: 'normal'}], topLabels: [{label: '(', labelType: 'normal'}]},
    {keyCode: '0', bottomLabels: [{label: '0', labelType: 'normal'}], topLabels: [{label: ')', labelType: 'normal'}]},
    {keyCode: '-', bottomLabels: [{label: '-', labelType: 'normal'}], topLabels: [{label: '_', labelType: 'normal'}]},
    {keyCode: '=', bottomLabels: [{label: '=', labelType: 'normal'}], topLabels: [{label: '+', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'u', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'i', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: 'ㅆ', labelType: 'trailing'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '[', labelType: 'normal'}], topLabels: [{label: '{', labelType: 'normal'}]},
    {keyCode: ']', bottomLabels: [{label: ']', labelType: 'normal'}], topLabels: [{label: '}', labelType: 'normal'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\', labelType: 'normal'}], topLabels: [{label: '|', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'f', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'g', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'j', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: ';', bottomLabels: [{label: ';', labelType: 'normal'}], topLabels: [{label: ':', labelType: 'normal'}]},
    {keyCode: '\'', bottomLabels: [{label: '\'', labelType: 'normal'}], topLabels: [{label: '"', labelType: 'normal'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}], topLabels: []},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'n', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: []},
    {keyCode: 'm', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: []},
    {keyCode: ',', bottomLabels: [{label: ',', labelType: 'normal'}], topLabels: [{label: '<', labelType: 'normal'}]},
    {keyCode: '.', bottomLabels: [{label: '.', labelType: 'normal'}], topLabels: [{label: '>', labelType: 'normal'}]},
    {keyCode: '/', bottomLabels: [{label: '/', labelType: 'normal'}], topLabels: [{label: '?', labelType: 'normal'}]},
  ],
];