import { KeyLabel } from "@/app/components/keyboard";

export const threeSet390Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '<'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '>'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '/'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '!'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '2'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '3'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSet390NoShiftLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅒ', labelType: 'vowel'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '<'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '>'}]},
    {keyCode: '[', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: '['}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: ']'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '/'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: '-'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: '='}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: '\\'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '!'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '2'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '3'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSet391Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '*'}], topLabels: [{label: '※'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: 'ㄿ', labelType: 'trailing'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: 'ㄾ', labelType: 'trailing'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '='}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '“'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: '”'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '\''}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: '~'}]},
    {keyCode: '-', bottomLabels: [{label: ')'}], topLabels: [{label: ';'}]},
    {keyCode: '=', bottomLabels: [{label: '>'}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㄵ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㄽ', labelType: 'trailing'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: '[', bottomLabels: [{label: '('}], topLabels: [{label: '%'}]},
    {keyCode: ']', bottomLabels: [{label: '<'}], topLabels: [{label: '/'}]},
    {keyCode: '\\', bottomLabels: [{label: ':'}], topLabels: [{label: '\\'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄼ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '2'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '3'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '·'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㄳ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '-'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '\"'}]},
    {keyCode: ',', bottomLabels: [{label: ','}]},
    {keyCode: '.', bottomLabels: [{label: '.'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '!'}]},
  ],
];
export const threeSet393Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: 'ㆆ', labelType: 'trailing'}], topLabels: [{label: 'ㆁ', labelType: 'trailing'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: 'ㅿ', labelType: 'trailing'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: ' 〯', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: ' 〮', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: 'ᅔᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ᅕᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: 'ㆁ', labelType: 'leading'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: 'ᅎᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: 'ᅐᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '!'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: 'ㅿ', labelType: 'leading'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: 'ㆆ', labelType: 'leading'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: 'ᄼᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: 'ᄾᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSet2015Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㄵ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}, {label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㄾ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: ':'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '2'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '3'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㄽ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㄿ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}, {label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: 'ㄳ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSet2015OldLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㆆ', labelType: 'trailing'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅢ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅿ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: ' 〯', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: ' 〮', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: 'ᅔᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ᅕᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '\''}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '"'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㆁ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '·'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: 'ㆁ', labelType: 'leading'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: 'ᅎᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: 'ᅐᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅌ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: 'ㅋ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '!'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: 'ㅿ', labelType: 'leading'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: 'ㆆ', labelType: 'leading'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: 'ᄼᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: 'ᄾᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSetP2Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㄾ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}, {label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㄽ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㄼ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㄿ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: ':'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '2'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '3'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㄳ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}, {label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㄵ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSetP3Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅂ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}, {label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: 'ㄾ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}, {label: 'ㅊ', labelType: 'trailing'}], topLabels: [{label: 'ㄽ', labelType: 'trailing'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '/'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}, {label: 'ㅎ', labelType: 'trailing'}], topLabels: [{label: 'ㄼ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}, {label: 'ㅍ', labelType: 'trailing'}], topLabels: [{label: 'ㄿ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '<'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '\"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}, {label: 'ㄷ', labelType: 'trailing'}], topLabels: [{label: 'ㄳ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}, {label: 'ㅈ', labelType: 'trailing'}], topLabels: [{label: 'ㄵ', labelType: 'trailing'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '>'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '2'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '3'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
];
export const threeSetD2Layout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅀ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅂ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: '7'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: '8'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: '9'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㅎ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: '4'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: '5'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: '6'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㄱ', labelType: 'trailing'}], topLabels: [{label: 'ㄲ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '<'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '>'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: '0'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: '1'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '2'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '3'}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
export const threeSetD2OldLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: 'ㅋ', labelType: 'trailing'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: 'ㅆ', labelType: 'trailing'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: 'ㅌ', labelType: 'trailing'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: 'ㅖ', labelType: 'vowel'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: 'ㅋ', labelType: 'leading'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅅ', labelType: 'trailing'}], topLabels: [{label: 'ㅿ', labelType: 'trailing'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㄹ', labelType: 'trailing'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: 'ㅂ', labelType: 'trailing'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㅊ', labelType: 'trailing'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㄹ', labelType: 'leading'}], topLabels: [{label: '\''}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㄷ', labelType: 'leading'}], topLabels: [{label: ' 〮', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅁ', labelType: 'leading'}], topLabels: [{label: 'ᅔᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅊ', labelType: 'leading'}], topLabels: [{label: 'ᅕᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅍ', labelType: 'leading'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅇ', labelType: 'trailing'}], topLabels: [{label: 'ㆁ', labelType: 'trailing'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'trailing'}], topLabels: [{label: 'ㆆ', labelType: 'trailing'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㅎ', labelType: 'trailing'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅍ', labelType: 'trailing'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: 'ㅈ', labelType: 'trailing'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㄴ', labelType: 'leading'}], topLabels: [{label: '"'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅇ', labelType: 'leading'}], topLabels: [{label: 'ㆁ', labelType: 'leading'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㄱ', labelType: 'leading'}], topLabels: [{label: 'ᅎᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅈ', labelType: 'leading'}], topLabels: [{label: 'ᅐᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅂ', labelType: 'leading'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: 'ㅌ', labelType: 'leading'}], topLabels: [{label: '/'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅁ', labelType: 'trailing'}], topLabels: [{label: 'ㄻ', labelType: 'trailing'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㆍ', labelType: 'vowel'}], topLabels: [{label: 'ㄱ', labelType: 'trailing'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㄷ', labelType: 'trailing'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '<'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: '>'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅅ', labelType: 'leading'}], topLabels: [{label: 'ㅿ', labelType: 'leading'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅎ', labelType: 'leading'}], topLabels: [{label: 'ㆆ', labelType: 'leading'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: 'ᄼᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: 'ᄾᅠ', labelType: 'leading', requiresOldHangulFont: true}]},
    {keyCode: '/', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}], topLabels: [{label: '?'}]},
  ],
]
