import { KeyLabel } from "@/app/components/keyboard";

export const twoSetLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: ';', bottomLabels: [{label: ';'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: '/'}], topLabels: [{label: '?'}]},
  ],
];
export const twoSetOldLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}], topLabels: [{label: ' 〯', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}], topLabels: [{label: ' 〮', labelType: 'tone', requiresOldHangulFont: true}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}], topLabels: [{label: 'ㅿ', labelType: 'consonant'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}], topLabels: [{label: 'ㆁ', labelType: 'consonant'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}], topLabels: [{label: 'ㆆ', labelType: 'consonant'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㆍ', labelType: 'vowel'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: ';', bottomLabels: [{label: ';'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}], topLabels: [{label: 'ᄼᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}], topLabels: [{label: 'ᄾᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}], topLabels: [{label: 'ᅎᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}], topLabels: [{label: 'ᅐᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: 'ᅔᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: 'ᅕᅠ', labelType: 'consonant', requiresOldHangulFont: true}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}], topLabels: [{label: '❖'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: '/'}], topLabels: [{label: '?'}]},
  ],
];
export const twoSetNorthLayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: ';', bottomLabels: [{label: ';'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: '/'}], topLabels: [{label: '?'}]},
  ],
];
export const dujulELayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}], topLabels: [{label: ';'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}]},
    {keyCode: ';', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: '/'}], topLabels: [{label: '?'}]},
  ],
];
export const dugyeobELayout: KeyLabel[][] = [
  [
    {keyCode: '`', bottomLabels: [{label: '₩'}], topLabels: [{label: '~'}]},
    {keyCode: '1', bottomLabels: [{label: '1'}], topLabels: [{label: '!'}]},
    {keyCode: '2', bottomLabels: [{label: '2'}], topLabels: [{label: '@'}]},
    {keyCode: '3', bottomLabels: [{label: '3'}], topLabels: [{label: '#'}]},
    {keyCode: '4', bottomLabels: [{label: '4'}], topLabels: [{label: '$'}]},
    {keyCode: '5', bottomLabels: [{label: '5'}], topLabels: [{label: '%'}]},
    {keyCode: '6', bottomLabels: [{label: '6'}], topLabels: [{label: '^'}]},
    {keyCode: '7', bottomLabels: [{label: '7'}], topLabels: [{label: '&'}]},
    {keyCode: '8', bottomLabels: [{label: '8'}], topLabels: [{label: '*'}]},
    {keyCode: '9', bottomLabels: [{label: '9'}], topLabels: [{label: '('}]},
    {keyCode: '0', bottomLabels: [{label: '0'}], topLabels: [{label: ')'}]},
    {keyCode: '-', bottomLabels: [{label: '-'}], topLabels: [{label: '_'}]},
    {keyCode: '=', bottomLabels: [{label: '='}], topLabels: [{label: '+'}]},
  ],
  [
    {keyCode: 'q', bottomLabels: [{label: 'ㅂ', labelType: 'consonant'}], topLabels: [{label: 'ㅃ', labelType: 'consonant'}]},
    {keyCode: 'w', bottomLabels: [{label: 'ㅈ', labelType: 'consonant'}], topLabels: [{label: 'ㅉ', labelType: 'consonant'}]},
    {keyCode: 'e', bottomLabels: [{label: 'ㄷ', labelType: 'consonant'}], topLabels: [{label: 'ㄸ', labelType: 'consonant'}]},
    {keyCode: 'r', bottomLabels: [{label: 'ㄱ', labelType: 'consonant'}], topLabels: [{label: 'ㄲ', labelType: 'consonant'}]},
    {keyCode: 't', bottomLabels: [{label: 'ㅅ', labelType: 'consonant'}], topLabels: [{label: 'ㅆ', labelType: 'consonant'}]},
    {keyCode: 'y', bottomLabels: [{label: 'ㅛ', labelType: 'vowel'}]},
    {keyCode: 'u', bottomLabels: [{label: 'ㅕ', labelType: 'vowel'}]},
    {keyCode: 'i', bottomLabels: [{label: 'ㅑ', labelType: 'vowel'}], topLabels: [{label: 'ㅆ', labelType: 'trailing'}]},
    {keyCode: 'o', bottomLabels: [{label: 'ㅐ', labelType: 'vowel'}], topLabels: [{label: 'ㅒ', labelType: 'vowel'}]},
    {keyCode: 'p', bottomLabels: [{label: 'ㅔ', labelType: 'vowel'}], topLabels: [{label: 'ㅖ', labelType: 'vowel'}]},
    {keyCode: '[', bottomLabels: [{label: '['}], topLabels: [{label: '{'}]},
    {keyCode: ']', bottomLabels: [{label: ']'}], topLabels: [{label: '}'}]},
    {keyCode: '\\', bottomLabels: [{label: '\\'}], topLabels: [{label: '|'}]},
  ],
  [
    {keyCode: 'a', bottomLabels: [{label: 'ㅁ', labelType: 'consonant'}]},
    {keyCode: 's', bottomLabels: [{label: 'ㄴ', labelType: 'consonant'}]},
    {keyCode: 'd', bottomLabels: [{label: 'ㅇ', labelType: 'consonant'}]},
    {keyCode: 'f', bottomLabels: [{label: 'ㄹ', labelType: 'consonant'}]},
    {keyCode: 'g', bottomLabels: [{label: 'ㅎ', labelType: 'consonant'}]},
    {keyCode: 'h', bottomLabels: [{label: 'ㅗ', labelType: 'vowel'}]},
    {keyCode: 'j', bottomLabels: [{label: 'ㅓ', labelType: 'vowel'}], topLabels: [{label: 'ㄶ', labelType: 'trailing'}]},
    {keyCode: 'k', bottomLabels: [{label: 'ㅏ', labelType: 'vowel'}], topLabels: [{label: 'ㅄ', labelType: 'trailing'}]},
    {keyCode: 'l', bottomLabels: [{label: 'ㅣ', labelType: 'vowel'}], topLabels: [{label: 'ㄺ', labelType: 'trailing'}]},
    {keyCode: ';', bottomLabels: [{label: ';'}], topLabels: [{label: ':'}]},
    {keyCode: '\'', bottomLabels: [{label: '\''}], topLabels: [{label: '"'}]},
  ],
  [
    {keyCode: 'z', bottomLabels: [{label: 'ㅋ', labelType: 'consonant'}]},
    {keyCode: 'x', bottomLabels: [{label: 'ㅌ', labelType: 'consonant'}]},
    {keyCode: 'c', bottomLabels: [{label: 'ㅊ', labelType: 'consonant'}]},
    {keyCode: 'v', bottomLabels: [{label: 'ㅍ', labelType: 'consonant'}]},
    {keyCode: 'b', bottomLabels: [{label: 'ㅠ', labelType: 'vowel'}]},
    {keyCode: 'n', bottomLabels: [{label: 'ㅜ', labelType: 'vowel'}]},
    {keyCode: 'm', bottomLabels: [{label: 'ㅡ', labelType: 'vowel'}]},
    {keyCode: ',', bottomLabels: [{label: ','}], topLabels: [{label: '<'}]},
    {keyCode: '.', bottomLabels: [{label: '.'}], topLabels: [{label: '>'}]},
    {keyCode: '/', bottomLabels: [{label: '/'}], topLabels: [{label: '?'}]},
  ],
];